"""Visualize QC metrics generated by proteomics_qc_summary.py."""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def load_summary(path):
    data = pd.read_csv(path)
    required = {"total_precursors", "q_value_below_0.01", "q_value_below_0.05"}
    missing = required - set(data.columns)
    if missing:
        raise ValueError(f"Missing required summary columns: {sorted(missing)}")
    if data.empty:
        raise ValueError("QC summary file is empty.")
    return data.iloc[0]


def create_qvalue_plot(summary, output_file):
    labels = ["Total precursors", "Q < 0.01", "Q < 0.05"]
    values = [
        summary["total_precursors"],
        summary["q_value_below_0.01"],
        summary["q_value_below_0.05"],
    ]
    output = Path(output_file)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(labels, values)
    ax.set_ylabel("Count")
    ax.set_title("DIA-NN QC: Q-value thresholds")
    fig.tight_layout()
    fig.savefig(output, dpi=150)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description="Plot generated DIA-NN QC summary metrics.")
    parser.add_argument("--input", default="results/proteomics_qc_summary.csv")
    parser.add_argument("--output", default="figures/qvalue_qc_summary.png")
    args = parser.parse_args()
    summary = load_summary(args.input)
    create_qvalue_plot(summary, args.output)
    print(f"QC figure saved to {args.output}")


if __name__ == "__main__":
    main()
